base_model: stabilityai/stablelm-3b-4e1t
base_model_config: stabilityai/stablelm-3b-4e1t
model_type: StableLMEpochForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

local_streaming_datasets: True
dataset_columns:
  - 'conversations'
datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_small/koishi-flan.jsonl'
    name: 'koishi-flan'
    type: pygmalion
    ds_type: 'json'
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_small/koishi-dolly.jsonl'
    name: 'koishi-dolly'
    type: pygmalion
    ds_type: 'json'

dataset_prepared_path: /workspace/dataset_prepared_path
output_dir: /workspace/stablelm-3b-instruct

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

wandb_project: stablelm-3b-instruct-stream-demo1
wandb_entity:
wandb_watch:
wandb_run_id: run7
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 8
optimizer: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 0.000001  # 0.00001 for better stability
lr_scheduler: cosine
learning_rate: 0.0001
weight_decay: 0.1
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention:
flash_attention: true

max_steps: 360  # Must for streaming. epochs * steps_per_epoch. steps_per_epoch ~ tokens/(seq_len * micro_batch_size * GPUs) = 5847355 / (4096*2*2)
logging_steps: 1  # max_steps * 0.002
warmup_steps: 10  # max_steps * 0.02
save_steps: 0.25  # 1 / epochs

val_set_size: 0
eval_steps:  # No split for streaming.
eval_table_size:
eval_table_max_new_tokens:
debug:
deepspeed: deepspeed/zero2.json
fsdp:
fsdp_config:
tokens:
  - "<|system|>"
  - "<|user|>"
  - "<|model|>"