base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

local_streaming_datasets: True
dataset_columns:
  - 'conversations'
datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_small/koishi-flan.jsonl'
    name: 'koishi-flan'
    type: pygmalion
    ds_type: 'json'
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_small/koishi-dolly.jsonl'
    name: 'koishi-dolly'
    type: pygmalion
    ds_type: 'json'
eval_datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_eval_small/koishi-flan.jsonl'
    name: 'koishi-flan'
    type: pygmalion
    ds_type: 'json'
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_eval_small/koishi-dolly.jsonl'
    name: 'koishi-dolly'
    type: pygmalion
    ds_type: 'json'

dataset_prepared_path: /workspace/dataset_prepared_path
output_dir: /workspace/mistral-7b-instruct

sequence_len: 8192
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

wandb_project: mistral-7b-instruct-stream-demo1
wandb_entity:
wandb_watch:
wandb_run_id: 
wandb_log_model:

dataloader_num_workers: 1
gradient_accumulation_steps: 12
micro_batch_size: 12
optimizer: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 0.000001  # 0.00001 for better stability
lr_scheduler: cosine
learning_rate: 0.0001
weight_decay: 0.1
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention:
flash_attention: true

max_steps: 120  # Must for streaming. epochs * steps_per_epoch. steps_per_epoch ~ tokens/(seq_len * micro_batch_size * accum-steps*GPUs) = 5847355 / (4096*6*2*2)
logging_steps: 1  # max_steps * 0.002
warmup_steps: 2  # max_steps * 0.02
save_steps: 0.5  # 1 / epochs
eval_steps: 12

val_set_size: 0
eval_table_size:
eval_table_max_new_tokens:
debug:
deepspeed: deepspeed/zero2.json
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "<|im_end|>"
  unk_token: "<unk>"
tokens:
  - "<|system|>"
  - "<|user|>"
  - "<|model|>"