base_model: /workspace/home/ck/Downloads/models
base_model_config: /workspace/home/ck/Downloads/models
tokenizer_type: AutoTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

dataset_columns:
  - 'conversations'
datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_chat_sharded/'
    name: 'chat'
    type: pygmalion
    ds_type: 'json'
eval_datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_chat_eval_sharded/'
    name: 'final_256_eval_jsonl'
    type: pygmalion
    ds_type: 'json'

dataset_prepared_path: /dataset_prepared_path
output_dir: /workspace/tinymistral_950m-chat

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: tinymistral_950m_chat
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

dataloader_num_workers: 1
#gradient_accumulation_steps: 3
#micro_batch_size: 26  # only primary loss, A100
gradient_accumulation_steps: 3
micro_batch_size: 16  # only primary loss, A6000
optimizer: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
adam_eps: 0.000000005
lr_scheduler: cosine
#learning_rate: 0.00005
learning_rate: 0.0002
weight_decay: 0.1
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention:
flash_attention: true

#A100
num_epochs: 1
logging_steps: 2
warmup_steps: 90
save_steps: 0.1  # 1 / epochs
eval_steps: 30
eval_batch_size: 8

val_set_size: 0
eval_table_size:
eval_table_max_new_tokens:
debug:
deepspeed: deepspeed/zero2_cosine.json
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<pad>"  # Try "<unk>"?
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
tokens:
  - "<|system|>"
  - "<|user|>"
  - "<|model|>"
  - "<|biden|>"
  - "<|trump|>"
  - "<|silence|>"