base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

local_streaming_datasets: True
dataset_columns:
  - 'text'
datasets:
  - path: '/workspace/home/ck/Downloads/final_join_256_jsonl_sharded_v2/'
    name: 'final_256_jsonl'
    type: completion
    ds_type: 'json'
eval_datasets:
  - path: '/workspace/home/ck/Downloads/final_join_256_eval_jsonl_mini2/'
    name: 'final_256_eval_jsonl'
    type: completion
    ds_type: 'json'

dataset_prepared_path: /workspace/dataset_prepared_path
output_dir: /workspace/mistral-7b-pretrain

sequence_len: 8192
sample_packing: true  # Try false? Also disable pad_to_sequence_len
eval_sample_packing: true
pad_to_sequence_len: true

wandb_project: mistral-7b-pretrain
wandb_entity:
wandb_watch:
wandb_run_id: 
wandb_log_model:

dataloader_num_workers: 12
gradient_accumulation_steps: 16
micro_batch_size: 6
optimizer: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 0.000001  # 0.00001 for better stability
lr_scheduler: cosine
learning_rate: 0.00003  # Official is 0.000025
weight_decay: 0.1
max_grad_norm: 1.0
# Official has dropout = 0.2 (but "didn't make much difference")

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention:
flash_attention: true

max_steps: 1200  # Must for streaming. epochs * steps_per_epoch. steps_per_epoch ~ tokens/(seq_len * micro_batch_size * accum-steps*GPUs)
logging_steps: 1  # max_steps * 0.002
warmup_steps: 60  # Official is 4% of max_steps
save_steps: 0.05  # 1 / epochs
eval_steps: 12

val_set_size: 0
eval_table_size:
eval_table_max_new_tokens:
debug:
deepspeed: deepspeed/zero2.json
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<pad>"  # Try "<unk>"?
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
tokens:
  - "<|system|>"
  - "<|user|>"
  - "<|model|>"