base_model: microsoft/phi-2
#base_model_config: microsoft/phi-2
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

local_streaming_datasets: True
dataset_columns:
  - 'conversations'
ordered_datasets: True
datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_sharded/'
    name: 'instruct'
    type: pygmalion
    ds_type: 'json'
eval_datasets:
  - path: '/workspace/home/ck/Downloads/convo_pygmalion_instruct_eval_sharded/'
    name: 'final_256_eval_jsonl'
    type: pygmalion
    ds_type: 'json'

dataset_prepared_path: /workspace/dataset_prepared_path
output_dir: /workspace/phi2-instruct

sequence_len: 2048
sample_packing: false  # currently unsupported
eval_sample_packing: false
pad_to_sequence_len:

wandb_project: phi2-instruct-stream-demo1
wandb_entity:
wandb_watch:
wandb_run_id: 
wandb_log_model:

dataloader_num_workers: 1
gradient_accumulation_steps: 2
micro_batch_size: 6
optimizer: paged_adamw_8bit
#adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 0.00001
lr_scheduler: cosine
learning_rate: 1e-5
weight_decay: 0.1
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
xformers_attention:
flash_attention: true

max_steps: 500  # Must for streaming. epochs * steps_per_epoch. steps_per_epoch ~ tokens/(seq_len * micro_batch_size * accum-steps * GPUs) = (332232000/5.5) / (4096*6*2*2)
logging_steps: 1
warmup_steps: 10
save_steps: 0.05  # 1 / epochs
eval_steps: 10

val_set_size: 0
eval_table_size:
eval_table_max_new_tokens:
debug:
deepspeed: deepspeed/zero2_cosine.json
fsdp:
fsdp_config:
tokens:
  - "<|system|>"
  - "<|user|>"
  - "<|model|>"
special_tokens:
  pad_token: "<|endoftext|>"

#resize_token_embeddings_to_32x: true